<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Backend\PeopleBank.Application\PeopleBank.Application.csproj" />
    <ProjectReference Include="..\..\src\Backend\PeopleBank.Domain\PeopleBank.Domain.csproj" />
    <ProjectReference Include="..\..\src\Backend\PeopleBank.Infrastructure\PeopleBank.Infrastructure.csproj" />
  </ItemGroup>

</Project>
